library(doParallel)  
library(stringr)

registerDoParallel()  
source("draw-tree.R")

doubleCheckfFunction <- function(parentFunction, functionName) {
	
	fbody <- capture.output(eval(parse(text = paste("body(",parentFunction, ")"))))

	pattern <- paste(functionName, "\\(", sep = "")
	
	hasParticularFunctionTotal <- str_detect(fbody, pattern)

	hasParticularFunction <- grepl('TRUE', toString(hasParticularFunctionTotal))

	return(hasParticularFunction)
}

findFunctionNamespace <- function(f , type="TOTAL") {
		f <- gsub(" ", "", f)

		names<-find(paste(f))

		if(type=="TOTAL") {
			n <- c()
			for(namespace in rev(names)) {
				if(namespace == ".GlobalEnv") {
					fName <- namespace
				} else {
					fName <- strsplit( namespace[[1]], ":")
					fName <- fName[[1]][2]
				}
				
				n <- c(n, fName)
			}
			fNamespace <-paste(n, sep="", collapse=";")
		} else {
			
			namespace <- tail(names, 1)
			if(namespace == ".GlobalEnv") {
				fNamespace <- namespace
			}else {
				
				fName <- strsplit( namespace[[1]], ":")
				fNamespace <- fName[[1]][2]
			}
		}

		return(fNamespace)
}


structureTreeDF <- function(f.expression, enablePrint=FALSE) {

	if(enablePrint) {cat("\n\n========== function:", f.expression, " ===========\n")}
	
	function.body <- eval(parse(text = paste("body(", f.expression, ")")))

	stuffsx <- as.character(function.body)

	DF <- data.frame(FunctionName=character(), TreeAspect=character(), Namespace=character(), AllNamespaces=character(), ComposedTree = character(), FunctID=character())

	print(length(stuffsx))
	if(length(stuffsx) > 8) {
	 	
		x <- foreach(majorElement = stuffsx) %dopar% {
			if(majorElement!="{" ){
				try(
					{
					sintaxTree <- call_tree_mod(parse(text=majorElement))
					outputAST <- capture.output(cat(sintaxTree, "\n"))			
					callTreeAnalysis(f.expression, DF, outputAST, enablePrint)
					
					}, silent=TRUE)
			}
		}
	
		for(df in x) {
			if(is.data.frame(df)){
				DF <- rbind(DF, df)
			}	
		}	 	

	} else {

		for (majorElement in stuffsx) {
			if(majorElement!="{" ){
				try(
					{sintaxTree <- call_tree_mod(parse(text=majorElement))
					outputAST <- capture.output(cat(sintaxTree, "\n"))
					updatedDF <- callTreeAnalysis(f.expression, DF, outputAST, enablePrint)
					DF <- updatedDF}, silent=TRUE)
			}
	 	}
	}
	
	#kable(DF)

	orderedDF <- DF[rev(order(DF$FunctionName)),]

	return(orderedDF)

}



callTreeAnalysis <- function(parentFunction, DF, outputAST, enablePrint) {

	majorTreeLevel <- 0				  #represents the identation level in the new tree, generated in this script
	identationLevel <- 0			  #represents the identation level in the tree generated by the "call_tree()" function

	previousTreeLevel <- 0 			  #saves the previous tree identation level, so that a behavior can be interpreted when moving on in the tree

	expressionsList <- list()		  #saves vectors of aspect (nameofexpression, currentIdentationLevel, majorTreeLevel), each time a new major identation occurs

	lastIfTreeLevel <- 0			  #used to identify the "Else If" and "Else" expressions, since they appear with a identation value of only one above the respective "If"

	insideNewIfClause <- FALSE
	insideNewElseIf <- FALSE
	insideNewElse <- FALSE

	insideIfArgumentsLookup <- FALSE  # used to identify if the "If" is processing the arguments or not. (arguments must have the same majorTreeLevel than the respective if)
	insideIfBodyLookup <- FALSE
	elseExpressionSuspect <- FALSE 	  # used to suspect of an "Else" expression when there is a reduce in the identation Level and appears a "{" bracket right away


	lastForTreeLevel <- 0
	insideForArgumentsLookup <- FALSE # used to identify if the "For" is processing the arguments or not. (arguments must have the same majorTreeLevel than the respective if)



	previousTreeElement <- ""

	printData <- c()

	for(line in outputAST) {

		
		lineSplit <- unlist(strsplit(line, "\\| "))

		# ------------------------------------------------------------------------------------------------
		#COUNTS THE NUMBER OF SPACES BEFORE THE SEPARATOR AND DIVIDES IT BY 2 TO FIND THE IDENTATION LEVEL
		currentTreeLevel <- nchar(lineSplit[1])/2

		treeElement <- lineSplit[2]
		treeElement <- gsub(" ", "", treeElement)
		if(is.na(treeElement)) {
			treeElement = "MISSING"
			currentTreeLevel <- previousTreeLevel}


		treeAspect <- c()

		# -------------------------------------------------------------
		# IF IS FUNCTION, THEN SAVES THE TREE_ELEMENT IN THE DATA FRAME
		if(isFunction(treeElement) && isMeaningful(treeElement)){ #these two depend from where the callTree_Analysis.R is called, and what it has imported 
	
		 	if(previousTreeElement == "()" || doubleCheckfFunction(parentFunction,treeElement)) {
				for(element in expressionsList) {
					
					if (length(expressionsList) > 0){
						treeAspect <- c(treeAspect,head(element,1))

					} else {
						treeAspect <- c(treeAspect,"")		
					}
				}

				collapsedTree <- paste(treeAspect, collapse = " / ")
				composedTree <- paste(c(treeAspect, treeElement), collapse = " / ")

				majorFNamespace <- findFunctionNamespace(treeElement, type="MAJOR")
				fNamespaces <- findFunctionNamespace(treeElement, type="TOTAL")
				functID <- paste(c(treeElement, majorFNamespace), collapse = "_")				
				DF <- rbind(DF, data.frame(FunctionName = treeElement, TreeAspect = collapsedTree, Namespace = majorFNamespace, AllNamespaces=fNamespaces, ComposedTree = composedTree, FunctID = functID ))
				
			}
		}


		if(treeElement == "if") {
			if((currentTreeLevel - lastIfTreeLevel) == 1 && lastIfTreeLevel != 0 ){
				if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "<< ELSEIF >>","\n"))}
				insideNewElseIf <- TRUE

			} else {
				if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "<< IF >>","\n"))}
				insideNewIfClause <- TRUE	
			}
			
			lastIfTreeLevel <- currentTreeLevel
			insideIfArgumentsLookup <- TRUE
			elseExpressionSuspect <- FALSE

		} else if(treeElement == "for") {
			if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "<< FOR >>","\n"))}

			lastForTreeLevel <- currentTreeLevel
			insideForArgumentsLookup <- TRUE

			expressionsList[[ length(expressionsList) + 1 ]] <- c(treeElement, currentTreeLevel, majorTreeLevel)
			
			elseExpressionSuspect <- FALSE

		} else if(insideIfArgumentsLookup) {
		
			if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "arg:  ", treeElement,"\n"))}

			# ----------------------------------------------------------------------------------------------------------------
			# IDENTIFIES WHEN DOES THE ARGUMENT ANALYSIS PHASE ENDS, MEANING, IT FINDS WHEN THE ACTUAL BODY OF THE "IF" STARTS
			
			if((currentTreeLevel < previousTreeLevel && currentTreeLevel == lastIfTreeLevel) || (treeElement != "()" && previousTreeElement == "if")){

				insideIfArgumentsLookup <-FALSE

				if(insideNewIfClause) {
					expressionsList[[ length(expressionsList) + 1 ]] <- c("if", currentTreeLevel, majorTreeLevel)
					insideNewIfClause <- FALSE
				} else if (insideNewElseIf) {
					expressionsList[[ length(expressionsList) + 1 ]] <- c("elseif", currentTreeLevel - 1, majorTreeLevel)
					insideNewElseIf <- FALSE
				}

				majorTreeLevel <- majorTreeLevel + 1
			}

			elseExpressionSuspect <- FALSE

		} else if(insideForArgumentsLookup) {
			
			if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "arg:  ", treeElement,"\n"))}

			if((currentTreeLevel - lastForTreeLevel)==1 && treeElement == "{"){ #currentTreeLevel < previousTreeLevel && 

				insideForArgumentsLookup <-FALSE

				majorTreeLevel <- majorTreeLevel + 1
			}

			elseExpressionSuspect <- FALSE	

		} else if (treeElement == "{" && elseExpressionSuspect) {
			
			if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), "<< ELSE >>","\n"))}

			expressionsList[[ length(expressionsList) + 1 ]] <- c("else", currentTreeLevel - 1, majorTreeLevel)
			majorTreeLevel <- majorTreeLevel + 1
			elseExpressionSuspect <- FALSE

		} else{
			elseExpressionSuspect <- FALSE
			if(enablePrint) {printData <- c(printData,paste(currentTreeLevel,"|\t", str_dup("    ", majorTreeLevel), treeElement,"\n"))}

			expressionsList_size <- length(expressionsList)

			if (expressionsList_size > 0) {
				
				lastElement_expressionsList <- expressionsList[[expressionsList_size]]
				
				expressionName_LastElement <- head(lastElement_expressionsList,3)[1]
				treeLevel_LastElement <- head(tail(lastElement_expressionsList,2),1)
				majorTreeLevel_LastElement <- tail(lastElement_expressionsList,1)


				#if the last treelevel element was an else if, it means that the tree level is going to be unmatched.
				#This happens because the "elseif" element is saved with a tree level less than it actually is, so it matches the "if" tree level
				if(expressionName_LastElement == "elseif") {
					treeLevel_LastElement <- as.integer(treeLevel_LastElement) + 1 
				}
				
				# gets the last treeLevelExpression that apeared in the code.
				# If the new value is smaller than the previous tree level, means that there was an expression
				if(currentTreeLevel < previousTreeLevel && as.numeric(currentTreeLevel) <= as.numeric(treeLevel_LastElement)) {
					if(enablePrint) {printData <- c(printData,paste("close\n"))}			

					# ------------------------------------------------------------------------------------------------
					# WHILE THE DIFFERENCE BETWEEN THE TREE LEVEL FROM THE LAST ELEMENT AND THE CURRENT TREE LEVEL 
					#IS GREATER THAN ONE, IT CONTINUES TO CLOSE THE TREE ELEMENTS OF THE LIST
					while(abs(as.numeric(treeLevel_LastElement) - as.numeric(currentTreeLevel)) > 1){ 
						
						expressionsList[[length(expressionsList)]] <- NULL

						expressionsList_newsize <- length(expressionsList)
						
						if (expressionsList_newsize == 0) {
							break
						}
						
						lastElement_expressionsList <- expressionsList[[expressionsList_newsize]]
						
						treeLevel_LastElement <- head(tail(lastElement_expressionsList,2),1)
						majorTreeLevel_LastElement <- tail(lastElement_expressionsList,1)
						
					}

					if(length(expressionsList) == 0) {
						majorTreeLevel <- 0

					} else {
						majorTreeLevel <- as.numeric(majorTreeLevel_LastElement)
					
						expressionsList[[length(expressionsList)]] <- NULL
						elseExpressionSuspect <- TRUE
					}
				}
			}
		}

		previousTreeLevel <- currentTreeLevel
		previousTreeElement <- treeElement
	}

	if(enablePrint) {printData <- c(printData,paste("\n###########################finish section #####################################\n\n\n"))}

	if(enablePrint) {cat(printData, "\n")}
	return(DF)
}





